function createfigure(cdata1, X1, Y1, cdata2, Y2, cdata3, XData1, YData1, zdata1, cdata4, Y3, zdata2, cdata5, Y4, zdata3, cdata6, Y5, zdata4, cdata7, Y6, cdata8, Y7)
%CREATEFIGURE(cdata1, X1, Y1, cdata2, Y2, cdata3, XData1, YData1, zdata1, cdata4, Y3, zdata2, cdata5, Y4, zdata3, cdata6, Y5, zdata4, cdata7, Y6, cdata8, Y7)
%  CDATA1:  image cdata
%  X1:  stem x
%  Y1:  stem y
%  CDATA2:  image cdata
%  Y2:  stem y
%  CDATA3:  image cdata
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  ZDATA1:  surface zdata
%  CDATA4:  image cdata
%  Y3:  stem y
%  ZDATA2:  surface zdata
%  CDATA5:  image cdata
%  Y4:  stem y
%  ZDATA3:  surface zdata
%  CDATA6:  image cdata
%  Y5:  stem y
%  ZDATA4:  surface zdata
%  CDATA7:  image cdata
%  Y6:  stem y
%  CDATA8:  image cdata
%  Y7:  stem y

%  Auto-generated by MATLAB on 31-Mar-2019 16:19:23

% Create figure
figure1 = figure('WindowState','maximized');
colormap(gray);

% Create sgtitle
sgtitle(figure1,'Comparison between image with noises and filtered images');

% Create subplot
subplot1 = subplot(7,4,1,'Parent',figure1);
hold(subplot1,'on');

% Create image
image(cdata1,'Parent',subplot1,'CDataMapping','scaled');

% Create title
title('image with noises');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0.5 254.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0.5 190.5]);
box(subplot1,'on');
axis(subplot1,'ij');
% Set the remaining axes properties
set(subplot1,'Layer','top');
% Create subplot
subplot2 = subplot(7,4,2,'Parent',figure1);
hold(subplot2,'on');

% Create stem
stem(X1,Y1,'Parent',subplot2,'Marker','none');

% Create title
title('histogram');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0 250]);
box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'XTickLabel','');
% Create subplot
subplot3 = subplot(7,4,5,'Parent',figure1);
hold(subplot3,'on');

% Create image
image(cdata2,'Parent',subplot3,'CDataMapping','scaled');

% Create title
title('image filtered with moving average');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0.5 256.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[0.5 192.5]);
box(subplot3,'on');
axis(subplot3,'ij');
% Set the remaining axes properties
set(subplot3,'Layer','top');
% Create subplot
subplot4 = subplot(7,4,6,'Parent',figure1);
hold(subplot4,'on');

% Create stem
stem(X1,Y2,'Parent',subplot4,'Marker','none');

% Create title
title('histogram');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[0 587.576457790814]);
box(subplot4,'on');
% Set the remaining axes properties
set(subplot4,'XTickLabel','');
% Create axes
axes1 = axes('Tag','colorstripe','Parent',figure1,...
    'Position',[0.336117021276596 0.716398809523809 0.156648936170213 0.00654910714285717]);
hold(axes1,'on');

% Create image
image([0.498046875 254.501953125],[0 1],cdata3,'Parent',axes1);

% Create line
line(XData1,YData1,'Parent',axes1,'Color',[0.15 0.15 0.15]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'Layer','top','YTickLabel','');
% Create subplot
subplot5 = subplot(7,4,7,'Parent',figure1);
hold(subplot5,'on');

% Create surf
surf(zdata1,'Parent',subplot5);

% Create title
title('filter with kernel 3x3');

view(subplot5,[-37.5 30]);
grid(subplot5,'on');
% Create subplot
subplot6 = subplot(7,4,8,'Parent',figure1);
hold(subplot6,'on');

% Create image
image(zdata1,'Parent',subplot6,'CDataMapping','scaled');

% Create title
title('filter with kernel 3x3');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot6,[0.5 9.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot6,[0.5 9.5]);
box(subplot6,'on');
axis(subplot6,'ij');
% Set the remaining axes properties
set(subplot6,'Layer','top');
% Create axes
axes2 = axes('Tag','colorstripe','Parent',figure1,...
    'Position',[0.336117021276596 0.844227678571429 0.156648936170213 0.0060579241071429]);
hold(axes2,'on');

% Create image
image([0.498046875 254.501953125],[0 1],cdata3,'Parent',axes2);

% Create line
line(XData1,YData1,'Parent',axes2,'Color',[0.15 0.15 0.15]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 1]);
box(axes2,'on');
axis(axes2,'ij');
% Set the remaining axes properties
set(axes2,'Layer','top','YTickLabel','');
% Create subplot
subplot7 = subplot(7,4,9,'Parent',figure1);
hold(subplot7,'on');

% Create image
image(cdata4,'Parent',subplot7,'CDataMapping','scaled');

% Create title
title('image filtered with moving average');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot7,[0.5 260.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot7,[0.5 196.5]);
box(subplot7,'on');
axis(subplot7,'ij');
% Set the remaining axes properties
set(subplot7,'Layer','top');
% Create subplot
subplot8 = subplot(7,4,10,'Parent',figure1);
hold(subplot8,'on');

% Create stem
stem(X1,Y3,'Parent',subplot8,'Marker','none');

% Create title
title('histogram');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot8,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot8,[0 723.023133220421]);
box(subplot8,'on');
% Set the remaining axes properties
set(subplot8,'XTickLabel','');
% Create axes
axes3 = axes('Tag','colorstripe','Parent',figure1,...
    'Position',[0.336117021276596 0.595119047619048 0.156648936170213 0.00654910714285717]);
hold(axes3,'on');

% Create image
image([0.498046875 254.501953125],[0 1],cdata3,'Parent',axes3);

% Create line
line(XData1,YData1,'Parent',axes3,'Color',[0.15 0.15 0.15]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 1]);
box(axes3,'on');
axis(axes3,'ij');
% Set the remaining axes properties
set(axes3,'Layer','top','YTickLabel','');
% Create subplot
subplot9 = subplot(7,4,11,'Parent',figure1);
hold(subplot9,'on');

% Create surf
surf(zdata2,'Parent',subplot9);

% Create title
title('filter with kernel 7x7');

view(subplot9,[-37.5 30]);
grid(subplot9,'on');
% Create subplot
subplot10 = subplot(7,4,12,'Parent',figure1);
hold(subplot10,'on');

% Create image
image(zdata2,'Parent',subplot10,'CDataMapping','scaled');

% Create title
title('filter with kernel 7x7');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot10,[0.5 13.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot10,[0.5 13.5]);
box(subplot10,'on');
axis(subplot10,'ij');
% Set the remaining axes properties
set(subplot10,'Layer','top');
% Create subplot
subplot11 = subplot(7,4,13,'Parent',figure1);
hold(subplot11,'on');

% Create image
image(cdata5,'Parent',subplot11,'CDataMapping','scaled');

% Create title
title('image filtered with Gaussian filter');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot11,[0.5 254.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot11,[0.5 190.5]);
box(subplot11,'on');
axis(subplot11,'ij');
% Set the remaining axes properties
set(subplot11,'Layer','top');
% Create subplot
subplot12 = subplot(7,4,14,'Parent',figure1);
hold(subplot12,'on');

% Create stem
stem(X1,Y4,'Parent',subplot12,'Marker','none');

% Create title
title('histogram');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot12,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot12,[0 600]);
box(subplot12,'on');
% Set the remaining axes properties
set(subplot12,'XTickLabel','');
% Create axes
axes4 = axes('Tag','colorstripe','Parent',figure1,...
    'Position',[0.336117021276596 0.473839285714286 0.156648936170213 0.00654910714285717]);
hold(axes4,'on');

% Create image
image([0.498046875 254.501953125],[0 1],cdata3,'Parent',axes4);

% Create line
line(XData1,YData1,'Parent',axes4,'Color',[0.15 0.15 0.15]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[0 1]);
box(axes4,'on');
axis(axes4,'ij');
% Set the remaining axes properties
set(axes4,'Layer','top','YTickLabel','');
% Create subplot
subplot13 = subplot(7,4,15,'Parent',figure1);
hold(subplot13,'on');

% Create surf
surf(zdata3,'Parent',subplot13);

% Create title
title('filter with kernel 3x3');

view(subplot13,[-37.5 30]);
grid(subplot13,'on');
% Create subplot
subplot14 = subplot(7,4,16,'Parent',figure1);
hold(subplot14,'on');

% Create image
image(zdata3,'Parent',subplot14,'CDataMapping','scaled');

% Create title
title('filter with kernel 3x3');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot14,[0.5 3.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot14,[0.5 3.5]);
box(subplot14,'on');
axis(subplot14,'ij');
% Set the remaining axes properties
set(subplot14,'Layer','top');
% Create subplot
subplot15 = subplot(7,4,17,'Parent',figure1);
hold(subplot15,'on');

% Create image
image(cdata6,'Parent',subplot15,'CDataMapping','scaled');

% Create title
title('image filtered with Gaussian filter');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot15,[0.5 254.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot15,[0.5 190.5]);
box(subplot15,'on');
axis(subplot15,'ij');
% Set the remaining axes properties
set(subplot15,'Layer','top');
% Create subplot
subplot16 = subplot(7,4,18,'Parent',figure1);
hold(subplot16,'on');

% Create stem
stem(X1,Y5,'Parent',subplot16,'Marker','none');

% Create title
title('histogram');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot16,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot16,[0 900]);
box(subplot16,'on');
% Set the remaining axes properties
set(subplot16,'XTickLabel','');
% Create axes
axes5 = axes('Tag','colorstripe','Parent',figure1,...
    'Position',[0.336117021276596 0.352559523809524 0.156648936170213 0.00654910714285711]);
hold(axes5,'on');

% Create image
image([0.498046875 254.501953125],[0 1],cdata3,'Parent',axes5);

% Create line
line(XData1,YData1,'Parent',axes5,'Color',[0.15 0.15 0.15]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[0 1]);
box(axes5,'on');
axis(axes5,'ij');
% Set the remaining axes properties
set(axes5,'Layer','top','YTickLabel','');
% Create subplot
subplot17 = subplot(7,4,19,'Parent',figure1);
hold(subplot17,'on');

% Create surf
surf(zdata4,'Parent',subplot17);

% Create title
title('filter with kernel 7x7');

view(subplot17,[-37.5 30]);
grid(subplot17,'on');
% Create subplot
subplot18 = subplot(7,4,20,'Parent',figure1);
hold(subplot18,'on');

% Create image
image(zdata4,'Parent',subplot18,'CDataMapping','scaled');

% Create title
title('filter with kernel 7x7');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot18,[0.5 7.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot18,[0.5 7.5]);
box(subplot18,'on');
axis(subplot18,'ij');
% Set the remaining axes properties
set(subplot18,'Layer','top');
% Create subplot
subplot19 = subplot(7,4,21,'Parent',figure1);
hold(subplot19,'on');

% Create image
image(cdata7,'Parent',subplot19,'CDataMapping','scaled');

% Create title
title('image filtered with median filter');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot19,[0.5 254.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot19,[0.5 190.5]);
box(subplot19,'on');
axis(subplot19,'ij');
% Set the remaining axes properties
set(subplot19,'Layer','top');
% Create subplot
subplot20 = subplot(7,4,22,'Parent',figure1);
hold(subplot20,'on');

% Create stem
stem(X1,Y6,'Parent',subplot20,'Marker','none');

% Create title
title('histogram');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot20,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot20,[0 400]);
box(subplot20,'on');
% Set the remaining axes properties
set(subplot20,'XTickLabel','');
% Create axes
axes6 = axes('Tag','colorstripe','Parent',figure1,...
    'Position',[0.336117021276596 0.231279761904762 0.156648936170213 0.00654910714285714]);
hold(axes6,'on');

% Create image
image([0.498046875 254.501953125],[0 1],cdata3,'Parent',axes6);

% Create line
line(XData1,YData1,'Parent',axes6,'Color',[0.15 0.15 0.15]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes6,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes6,[0 1]);
box(axes6,'on');
axis(axes6,'ij');
% Set the remaining axes properties
set(axes6,'Layer','top','YTickLabel','');
% Create subplot
subplot21 = subplot(7,4,25,'Parent',figure1);
hold(subplot21,'on');

% Create image
image(cdata8,'Parent',subplot21,'CDataMapping','scaled');

% Create title
title('image filtered with median filter');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot21,[0.5 254.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot21,[0.5 190.5]);
box(subplot21,'on');
axis(subplot21,'ij');
% Set the remaining axes properties
set(subplot21,'Layer','top');
% Create subplot
subplot22 = subplot(7,4,26,'Parent',figure1);
hold(subplot22,'on');

% Create stem
stem(X1,Y7,'Parent',subplot22,'Marker','none');

% Create title
title('histogram');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot22,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot22,[0 400]);
box(subplot22,'on');
% Set the remaining axes properties
set(subplot22,'XTickLabel','');
% Create axes
axes7 = axes('Tag','colorstripe','Parent',figure1,...
    'Position',[0.336117021276596 0.11 0.156648936170213 0.00654910714285714]);
hold(axes7,'on');

% Create image
image([0.498046875 254.501953125],[0 1],cdata3,'Parent',axes7);

% Create line
line(XData1,YData1,'Parent',axes7,'Color',[0.15 0.15 0.15]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes7,[0 255]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes7,[0 1]);
box(axes7,'on');
axis(axes7,'ij');
% Set the remaining axes properties
set(axes7,'Layer','top','YTickLabel','');
